paths:
  /api/products:
    get:
      summary: Endpoint para obtener todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Se obtuvieron correctamente los productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "401":
          description: Acceso no autorizado al endpoint
        "500":
          description: Error interno del servidor
    post:
      summary: Da de alta un nuevo producto.
      tags:
        - Productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/UpdateProduct"
      responses:
        "200":
          description: El producto de creó correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
        "400":
          description: No tiene autorización para realizar la operación.

  /api/products/{pid}:
    get:
      summary: Devuelve la información de un producto.
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto
          schema:
            type: string
      responses:
        "200":
          description: Se obtuvo correctamente el producto.
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Product"
    put:
      summary: Actualiza la información de un producto.
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/UpdateProduct"
      responses:
        "200":
          description: El producto de actualizó correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
        "400":
          description: No tiene autorización para actualizar el producto.
    delete:
      summary: Elimina un producto.
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto que será eliminado.
          schema:
            type: string
      responses:
        "200":
          description: El producto de eliminó correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
        "400":
          description: No tiene autorización para eliminar el producto.

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: id del producto generado por MongoDB
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto.
        price:
          type: numeric
          description: Precio del producto
        code:
          type: string
          description: Código del producto
        stock:
          type: numeric
          description: Stock del producto
        status:
          type: string
          description: Estado del producto
        category:
          type: string
          description: Categoría del producto
        owner:
          type: string
          description: Propietario (creador) del producto
      example:
        _id: k89quwekjalsdu
        title: "Alfajor de dulce de leche"
  requestBodies:
    UpdateProduct:
      type: object
      properties:
        _id:
          type: ObjectId
          description: id del producto generado por MongoDB
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto.
        price:
          type: numeric
          description: Precio del producto
        code:
          type: string
          description: Código del producto
        stock:
          type: numeric
          description: Stock del producto
        status:
          type: string
          description: Estado del producto
        category:
          type: string
          description: Categoría del producto
      example:
        title: "Alfajor de dulce de leche"